### ISSUE TITLE
Create vector images for the book/site

### ISSUE THREAD

**Issue by jenweber** [ember-learn/the-shortest-ember-book#2]
@BradenLawrence do you want to help with these? Each can be individually PR'd if you'd like. The final result should be a web-friendly SVG so we can easily edit in the future. They should go in `public/images` folder.

- [x] battery
- [x] button
- [ ] url bar
- [x] something creative for testing
- [x] Data image (bucket)
- [ ] deployment rainbows, sparkles, unicorns, whatevs
- [x] development roadmap... an actual road? A map?
- [ ] JS heart tattoo

~I'll ask Ember Observer about whether they can lend some spaceships~ Ember Observer's only asset is the logo, so we should make a thing

**Comment by BradenLawrence** [comment]
Sure thing! I took a stab at the first button image in your concept sketches. You had mentioned doing a sketchbook style, so did a few tests following that theme. Here are a few different directions we could go:
![shortestemberbook_button_styleoptions](https://user-images.githubusercontent.com/17574170/38780911-6658228a-40ab-11e8-883b-79913265f222.png)

1. Simplest look, I'm thinking we could apply some kind of texture to this to make it feel more hand drawn.
2. A more vector look with enough complexity that it wouldn't need a texture.
3. A 'sticker' style inspired by the white outlined Ember logo.
4. A variation on the above with a peeled corner effect.

Any thoughts on these? I could do a few more variations on one or two of them.

@locks

**Comment by jenweber** [comment]
![front-page](https://user-images.githubusercontent.com/16627268/40882697-b03225fe-66b7-11e8-8f6d-708da616b025.jpg)
